// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Oficina.Execucao.Api.IntegrationTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class FluxoDeExecucaoDaOficinaFeature : object, Xunit.IClassFixture<FluxoDeExecucaoDaOficinaFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "FluxoExecucao.feature"
#line hidden
        
        public FluxoDeExecucaoDaOficinaFeature(FluxoDeExecucaoDaOficinaFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Fluxo de Execução da Oficina", ("  Como mecânico da oficina\r\n  Quero registrar o diagnóstico, propor orçamento, in" +
                    "iciar e finalizar a execução\r\n  Para que o estado da OS seja atualizado e a Saga" +
                    " avance pelos eventos publicados"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Iniciar diagnóstico publica evento DiagnosticoIniciado")]
        [Xunit.TraitAttribute("FeatureTitle", "Fluxo de Execução da Oficina")]
        [Xunit.TraitAttribute("Description", "Iniciar diagnóstico publica evento DiagnosticoIniciado")]
        public async System.Threading.Tasks.Task IniciarDiagnosticoPublicaEventoDiagnosticoIniciado()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Iniciar diagnóstico publica evento DiagnosticoIniciado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("que existe uma OS \"ABC1234\" na fila aguardando diagnóstico", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.WhenAsync("o mecânico \"Carlos\" inicia o diagnóstico", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 10
    await testRunner.ThenAsync("o evento \"DiagnosticoIniciado\" é publicado com o mecânico \"Carlos\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 11
    await testRunner.AndAsync("a execução fica com status \"EmDiagnostico\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Propor orçamento publica OrcamentoPropostoPelaOficina")]
        [Xunit.TraitAttribute("FeatureTitle", "Fluxo de Execução da Oficina")]
        [Xunit.TraitAttribute("Description", "Propor orçamento publica OrcamentoPropostoPelaOficina")]
        public async System.Threading.Tasks.Task ProporOrcamentoPublicaOrcamentoPropostoPelaOficina()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Propor orçamento publica OrcamentoPropostoPelaOficina", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
    await testRunner.GivenAsync("que existe uma OS \"DEF5678\" em diagnóstico", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 15
    await testRunner.WhenAsync("o mecânico propõe um orçamento de 350.00 com 1 item", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 16
    await testRunner.ThenAsync("o evento \"OrcamentoPropostoPelaOficina\" é publicado com valor 350.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 17
    await testRunner.AndAsync("a execução fica com status \"AguardandoOrcamento\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Finalizar execução publica ExecucaoFinalizada")]
        [Xunit.TraitAttribute("FeatureTitle", "Fluxo de Execução da Oficina")]
        [Xunit.TraitAttribute("Description", "Finalizar execução publica ExecucaoFinalizada")]
        public async System.Threading.Tasks.Task FinalizarExecucaoPublicaExecucaoFinalizada()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Finalizar execução publica ExecucaoFinalizada", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
    await testRunner.GivenAsync("que existe uma OS \"GHI9012\" em execução", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 21
    await testRunner.WhenAsync("o mecânico finaliza a execução", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 22
    await testRunner.ThenAsync("o evento \"ExecucaoFinalizada\" é publicado no barramento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 23
    await testRunner.AndAsync("a execução fica com status \"Finalizada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await FluxoDeExecucaoDaOficinaFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await FluxoDeExecucaoDaOficinaFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
